# Generated by Django 3.2.6 on 2022-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='api_docentes',
            field=models.JSONField(null=True),
        ),
    ]
