# Generated by Django 3.2.6 on 2022-10-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_docente_api_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='api_defesas',
            field=models.JSONField(null=True),
        ),
    ]
